### PR TITLE
Fix Header Addition Form 

### PR DESCRIPTION
**Pull request by brettgus**
Re-creating this PR as I unintentionally closed the previous one. 

Incorporating [this fix](https://github.com/gophish/gophish/commit/741201b7f09a0a0fd8ed778da057adc371b4b92b) that will allow for adding custom headers in the sending profile again. Fixes issue #74

### CODE REVIEW

**Comment by fin3ss3g0d** [comment]
It's clearly not easy to read what the actual changes are, and this is a feature I haven't seen myself needing to use. If the actual change could be highlighted in greater detail, that would be great. I don't merge anything without testing it myself, and I'm not digging through that for a feature I won't use myself.

**Comment by brettgus** [comment]
I was only incorporating [the fix from Gophish itself](https://github.com/gophish/gophish/commit/741201b7f09a0a0fd8ed778da057adc371b4b92b).

[Here](https://gistpreview.github.io/?6e60dfe77e86742c48b859508cc601b0) is a diff of the change

**Comment by fin3ss3g0d** [comment]
I apologize for making it seem like the frustration was directed towards you, upon looking at the commit you are referencing from gophish, the developer(s) seem to have only made changes to the minified version of the JavaScript files and not the originals. This is actually very poor development practice, as you can see it makes readability almost impossible and any form of maintenance like this. This is all I see from the GitHub diff:

image

There is no way to tell what actually got changed from that. Thank you for providing the enhanced diff, sponsors will get first dibs on the fix.

**Comment by fin3ss3g0d** [comment]
Implemented in the sponsors repository, coming to the public repository in the future.

**Pull request closed without merging**
